# Generated by Django 3.2.6 on 2021-08-25 06:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('recipe', models.TextField(max_length=2000, verbose_name='рецепт')),
                ('cooking_time', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='время готовки')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
            },
        ),
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('units', models.CharField(max_length=20, verbose_name='единицы измерения')),
            ],
            options={
                'verbose_name': 'ингридиент',
                'verbose_name_plural': 'ингридиенты',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(blank=True, choices=[('BREAKFAST', 'завтрак'), ('LUNCH', 'обед'), ('DINNER', 'ужин')], db_index=True, max_length=20, verbose_name='тип приема пищи')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='число')),
                ('date', models.DateField(db_index=True, verbose_name='дата')),
            ],
            options={
                'verbose_name': 'прием пищи',
                'verbose_name_plural': 'приемы пищи',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('dishes', models.ManyToManyField(related_name='tags', to='cuisine.Dish', verbose_name='блюда')),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'тэги',
            },
        ),
        migrations.CreateModel(
            name='MealPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='число блюд')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_positions', to='cuisine.dish', verbose_name='блюдо')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_positions', to='cuisine.meal', verbose_name='прием пищи')),
            ],
            options={
                'verbose_name': 'позиция приема пищи',
                'verbose_name_plural': 'позиции приема пищи',
            },
        ),
        migrations.CreateModel(
            name='IngridientPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='число')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='cuisine.dish', verbose_name='блюдо')),
                ('ingridient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='позиция', to='cuisine.ingridient', verbose_name='ингридиент')),
            ],
            options={
                'verbose_name': 'позиция ингридиентов блюда',
                'verbose_name_plural': 'позиции ингридиентов блюда',
            },
        ),
    ]
