# Generated by Django 3.2.6 on 2021-08-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='tag',
            name='dishes',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='cuisine.Dish', verbose_name='блюда'),
        ),
    ]
