# Generated by Django 3.2.6 on 2021-08-25 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuisine', '0002_auto_20210825_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='auth.user', verbose_name='пользователь'),
            preserve_default=False,
        ),
    ]
