# Generated by Django 3.2.6 on 2021-08-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0003_meal_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
    ]
