# Generated by Django 3.1.7 on 2021-08-25 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0003_meal_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('units', models.CharField(max_length=20, verbose_name='единицы измерения')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='IngredientPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='число')),
            ],
            options={
                'verbose_name': 'позиция ингредиентов блюда',
                'verbose_name_plural': 'позиции ингредиентов блюда',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('menu_type', models.CharField(blank=True, choices=[('DAILY', 'ежедневное'), ('WEEKLY', 'недельное')], db_index=True, max_length=20, verbose_name='тип приема пищи')),
            ],
            options={
                'verbose_name': 'тип меню',
                'verbose_name_plural': 'типы меню',
            },
        ),
        migrations.RemoveField(
            model_name='ingridientposition',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='ingridientposition',
            name='ingridient',
        ),
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mealposition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Ingridient',
        ),
        migrations.DeleteModel(
            name='IngridientPosition',
        ),
        migrations.AddField(
            model_name='ingredientposition',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='cuisine.dish', verbose_name='блюдо'),
        ),
        migrations.AddField(
            model_name='ingredientposition',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='cuisine.ingredient', verbose_name='ингредиент'),
        ),
        migrations.AddField(
            model_name='dish',
            name='menu_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes', to='cuisine.MenuCategory', verbose_name='категория меню'),
        ),
    ]
