# Generated by Django 3.2.6 on 2021-08-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0004_rename_ingridient_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngridientPosition',
            new_name='IngredientPosition',
        ),
        migrations.RenameField(
            model_name='ingredientposition',
            old_name='ingridient',
            new_name='ingredient',
        ),
        migrations.AlterField(
            model_name='tag',
            name='dishes',
            field=models.ManyToManyField(related_name='tags', to='cuisine.Dish', verbose_name='блюда'),
        ),
    ]
