# Generated by Django 3.1.7 on 2021-08-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0004_auto_20210825_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='menu_category',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='dishes',
            field=models.ManyToManyField(blank=True, null=True, related_name='menu_category', to='cuisine.Dish', verbose_name='блюда'),
        ),
    ]
