# Generated by Django 3.2.6 on 2021-08-25 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0005_auto_20210825_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'ингредиент', 'verbose_name_plural': 'ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientposition',
            options={'verbose_name': 'позиция ингредиентов блюда', 'verbose_name_plural': 'позиции ингредиентов блюда'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='ingredientposition',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='позиция', to='cuisine.ingredient', verbose_name='ингредиент'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='dishes',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='cuisine.Dish', verbose_name='блюда'),
        ),
    ]
