# Generated by Django 3.2.6 on 2021-08-26 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0006_auto_20210825_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientposition',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='cuisine.ingredient', verbose_name='ингредиент'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='dishes',
            field=models.ManyToManyField(related_name='tags', to='cuisine.Dish', verbose_name='блюда'),
        ),
    ]
